MAX_NO_ACTIVITIES = 43

DEFAULT_DEC_FACTOR = 0.23
DEFAULT_DFG_CLEAN_MULTIPLIER = 0.5

PARAM_MOST_COMMON_VARIANT = "most_common_variant"
PARAM_MOST_COMMON_PATHS = "most_common_paths"

MAX_NO_CASES_TO_RETURN = 400
MAX_NO_VARIANTS_TO_RETURN = 100
MAX_NO_EVENTS_PER_DOTTED = 10000

DEFAULT_CLASSIFIER_KEY = "@@classifier"
DEFAULT_EVENT_INDEX_KEY = "@@event_index"
DEFAULT_CASE_INDEX_KEY = "@@case_index"
