MAX_NO_ACTIVITIES = 43

DEFAULT_DEC_FACTOR = 0.23
DEFAULT_DFG_CLEAN_MULTIPLIER = 0.5

PARAM_MOST_COMMON_VARIANT = "most_common_variant"
PARAM_MOST_COMMON_PATHS = "most_common_paths"

MAX_NO_CASES_TO_RETURN = 400
MAX_NO_VARIANTS_TO_RETURN = 100